apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sIngressGIPImmutable
metadata:
  name: ingress-gip-immutable
spec:
  match:
    kinds:
      - apiGroups: ["extensions"]
        kinds: ["Ingress"]

